// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IrrigationService.proto

package com.lekkss.irrigation.irrigationservice;

public interface IrrigationResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lekkss.irrigation.IrrigationResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool irrigation_needed = 1;</code>
   */
  boolean getIrrigationNeeded();
}
