// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IrrigationService.proto

package com.lekkss.irrigation.irrigationservice;

public interface SoilDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lekkss.irrigation.SoilData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();

  /**
   * <code>double soil_nutrients = 2;</code>
   */
  double getSoilNutrients();

  /**
   * <code>double soil_humidity = 3;</code>
   */
  double getSoilHumidity();
}
