// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IrrigationService.proto

package com.lekkss.irrigation.irrigationservice;

public interface ToggleIrrigationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lekkss.irrigation.ToggleIrrigationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enable_irrigation = 1;</code>
   */
  boolean getEnableIrrigation();
}
