// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IrrigationService.proto

package com.lekkss.irrigation.irrigationservice;

public interface ToggleIrrigationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lekkss.irrigation.ToggleIrrigationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
