// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SoilSensorService.proto

package com.lekkss.soilsensor.soilsensorservice;

/**
 * Protobuf type {@code com.lekkss.soilsensor.SoilData}
 */
public  final class SoilData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lekkss.soilsensor.SoilData)
    SoilDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SoilData.newBuilder() to construct.
  private SoilData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SoilData() {
    timeOfDay_ = "";
    temperature_ = 0D;
    soilNutrients_ = 0D;
    soilHumidity_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SoilData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            timeOfDay_ = s;
            break;
          }
          case 17: {

            temperature_ = input.readDouble();
            break;
          }
          case 25: {

            soilNutrients_ = input.readDouble();
            break;
          }
          case 33: {

            soilHumidity_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lekkss.soilsensor.soilsensorservice.SoilSensorServiceProto.internal_static_com_lekkss_soilsensor_SoilData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lekkss.soilsensor.soilsensorservice.SoilSensorServiceProto.internal_static_com_lekkss_soilsensor_SoilData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lekkss.soilsensor.soilsensorservice.SoilData.class, com.lekkss.soilsensor.soilsensorservice.SoilData.Builder.class);
  }

  public static final int TIME_OF_DAY_FIELD_NUMBER = 1;
  private volatile java.lang.Object timeOfDay_;
  /**
   * <code>string time_of_day = 1;</code>
   */
  public java.lang.String getTimeOfDay() {
    java.lang.Object ref = timeOfDay_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeOfDay_ = s;
      return s;
    }
  }
  /**
   * <code>string time_of_day = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTimeOfDayBytes() {
    java.lang.Object ref = timeOfDay_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeOfDay_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 2;
  private double temperature_;
  /**
   * <code>double temperature = 2;</code>
   */
  public double getTemperature() {
    return temperature_;
  }

  public static final int SOIL_NUTRIENTS_FIELD_NUMBER = 3;
  private double soilNutrients_;
  /**
   * <code>double soil_nutrients = 3;</code>
   */
  public double getSoilNutrients() {
    return soilNutrients_;
  }

  public static final int SOIL_HUMIDITY_FIELD_NUMBER = 4;
  private double soilHumidity_;
  /**
   * <code>double soil_humidity = 4;</code>
   */
  public double getSoilHumidity() {
    return soilHumidity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTimeOfDayBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeOfDay_);
    }
    if (temperature_ != 0D) {
      output.writeDouble(2, temperature_);
    }
    if (soilNutrients_ != 0D) {
      output.writeDouble(3, soilNutrients_);
    }
    if (soilHumidity_ != 0D) {
      output.writeDouble(4, soilHumidity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTimeOfDayBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timeOfDay_);
    }
    if (temperature_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, temperature_);
    }
    if (soilNutrients_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, soilNutrients_);
    }
    if (soilHumidity_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, soilHumidity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lekkss.soilsensor.soilsensorservice.SoilData)) {
      return super.equals(obj);
    }
    com.lekkss.soilsensor.soilsensorservice.SoilData other = (com.lekkss.soilsensor.soilsensorservice.SoilData) obj;

    boolean result = true;
    result = result && getTimeOfDay()
        .equals(other.getTimeOfDay());
    result = result && (
        java.lang.Double.doubleToLongBits(getTemperature())
        == java.lang.Double.doubleToLongBits(
            other.getTemperature()));
    result = result && (
        java.lang.Double.doubleToLongBits(getSoilNutrients())
        == java.lang.Double.doubleToLongBits(
            other.getSoilNutrients()));
    result = result && (
        java.lang.Double.doubleToLongBits(getSoilHumidity())
        == java.lang.Double.doubleToLongBits(
            other.getSoilHumidity()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_OF_DAY_FIELD_NUMBER;
    hash = (53 * hash) + getTimeOfDay().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperature()));
    hash = (37 * hash) + SOIL_NUTRIENTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSoilNutrients()));
    hash = (37 * hash) + SOIL_HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSoilHumidity()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lekkss.soilsensor.soilsensorservice.SoilData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lekkss.soilsensor.soilsensorservice.SoilData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.lekkss.soilsensor.SoilData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lekkss.soilsensor.SoilData)
      com.lekkss.soilsensor.soilsensorservice.SoilDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lekkss.soilsensor.soilsensorservice.SoilSensorServiceProto.internal_static_com_lekkss_soilsensor_SoilData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lekkss.soilsensor.soilsensorservice.SoilSensorServiceProto.internal_static_com_lekkss_soilsensor_SoilData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lekkss.soilsensor.soilsensorservice.SoilData.class, com.lekkss.soilsensor.soilsensorservice.SoilData.Builder.class);
    }

    // Construct using com.lekkss.soilsensor.soilsensorservice.SoilData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timeOfDay_ = "";

      temperature_ = 0D;

      soilNutrients_ = 0D;

      soilHumidity_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lekkss.soilsensor.soilsensorservice.SoilSensorServiceProto.internal_static_com_lekkss_soilsensor_SoilData_descriptor;
    }

    @java.lang.Override
    public com.lekkss.soilsensor.soilsensorservice.SoilData getDefaultInstanceForType() {
      return com.lekkss.soilsensor.soilsensorservice.SoilData.getDefaultInstance();
    }

    @java.lang.Override
    public com.lekkss.soilsensor.soilsensorservice.SoilData build() {
      com.lekkss.soilsensor.soilsensorservice.SoilData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lekkss.soilsensor.soilsensorservice.SoilData buildPartial() {
      com.lekkss.soilsensor.soilsensorservice.SoilData result = new com.lekkss.soilsensor.soilsensorservice.SoilData(this);
      result.timeOfDay_ = timeOfDay_;
      result.temperature_ = temperature_;
      result.soilNutrients_ = soilNutrients_;
      result.soilHumidity_ = soilHumidity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lekkss.soilsensor.soilsensorservice.SoilData) {
        return mergeFrom((com.lekkss.soilsensor.soilsensorservice.SoilData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lekkss.soilsensor.soilsensorservice.SoilData other) {
      if (other == com.lekkss.soilsensor.soilsensorservice.SoilData.getDefaultInstance()) return this;
      if (!other.getTimeOfDay().isEmpty()) {
        timeOfDay_ = other.timeOfDay_;
        onChanged();
      }
      if (other.getTemperature() != 0D) {
        setTemperature(other.getTemperature());
      }
      if (other.getSoilNutrients() != 0D) {
        setSoilNutrients(other.getSoilNutrients());
      }
      if (other.getSoilHumidity() != 0D) {
        setSoilHumidity(other.getSoilHumidity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lekkss.soilsensor.soilsensorservice.SoilData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lekkss.soilsensor.soilsensorservice.SoilData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object timeOfDay_ = "";
    /**
     * <code>string time_of_day = 1;</code>
     */
    public java.lang.String getTimeOfDay() {
      java.lang.Object ref = timeOfDay_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeOfDay_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string time_of_day = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimeOfDayBytes() {
      java.lang.Object ref = timeOfDay_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeOfDay_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string time_of_day = 1;</code>
     */
    public Builder setTimeOfDay(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeOfDay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string time_of_day = 1;</code>
     */
    public Builder clearTimeOfDay() {
      
      timeOfDay_ = getDefaultInstance().getTimeOfDay();
      onChanged();
      return this;
    }
    /**
     * <code>string time_of_day = 1;</code>
     */
    public Builder setTimeOfDayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeOfDay_ = value;
      onChanged();
      return this;
    }

    private double temperature_ ;
    /**
     * <code>double temperature = 2;</code>
     */
    public double getTemperature() {
      return temperature_;
    }
    /**
     * <code>double temperature = 2;</code>
     */
    public Builder setTemperature(double value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double temperature = 2;</code>
     */
    public Builder clearTemperature() {
      
      temperature_ = 0D;
      onChanged();
      return this;
    }

    private double soilNutrients_ ;
    /**
     * <code>double soil_nutrients = 3;</code>
     */
    public double getSoilNutrients() {
      return soilNutrients_;
    }
    /**
     * <code>double soil_nutrients = 3;</code>
     */
    public Builder setSoilNutrients(double value) {
      
      soilNutrients_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double soil_nutrients = 3;</code>
     */
    public Builder clearSoilNutrients() {
      
      soilNutrients_ = 0D;
      onChanged();
      return this;
    }

    private double soilHumidity_ ;
    /**
     * <code>double soil_humidity = 4;</code>
     */
    public double getSoilHumidity() {
      return soilHumidity_;
    }
    /**
     * <code>double soil_humidity = 4;</code>
     */
    public Builder setSoilHumidity(double value) {
      
      soilHumidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double soil_humidity = 4;</code>
     */
    public Builder clearSoilHumidity() {
      
      soilHumidity_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lekkss.soilsensor.SoilData)
  }

  // @@protoc_insertion_point(class_scope:com.lekkss.soilsensor.SoilData)
  private static final com.lekkss.soilsensor.soilsensorservice.SoilData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lekkss.soilsensor.soilsensorservice.SoilData();
  }

  public static com.lekkss.soilsensor.soilsensorservice.SoilData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SoilData>
      PARSER = new com.google.protobuf.AbstractParser<SoilData>() {
    @java.lang.Override
    public SoilData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SoilData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SoilData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SoilData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lekkss.soilsensor.soilsensorservice.SoilData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

