// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SoilSensorService.proto

package com.lekkss.soilsensor.soilsensorservice;

public interface SoilDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lekkss.soilsensor.SoilData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time_of_day = 1;</code>
   */
  java.lang.String getTimeOfDay();
  /**
   * <code>string time_of_day = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimeOfDayBytes();

  /**
   * <code>double temperature = 2;</code>
   */
  double getTemperature();

  /**
   * <code>double soil_nutrients = 3;</code>
   */
  double getSoilNutrients();

  /**
   * <code>double soil_humidity = 4;</code>
   */
  double getSoilHumidity();
}
