// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SoilSensorService.proto

package com.lekkss.soilsensor.soilsensorservice;

public interface StreamSoilDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lekkss.soilsensor.StreamSoilDataRequest)
    com.google.protobuf.MessageOrBuilder {
}
