// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeatherSensorService.proto

package com.lekkss.weathersensor.weathersensorservice;

public interface LocationCoordinatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lekkss.weathersensor.LocationCoordinates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitude = 1;</code>
   */
  double getLatitude();

  /**
   * <code>double longitude = 2;</code>
   */
  double getLongitude();
}
