// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeatherSensorService.proto

package com.lekkss.weathersensor.weathersensorservice;

/**
 * Protobuf type {@code com.lekkss.weathersensor.WeatherData}
 */
public  final class WeatherData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lekkss.weathersensor.WeatherData)
    WeatherDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherData.newBuilder() to construct.
  private WeatherData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherData() {
    temperature_ = 0D;
    humidity_ = 0D;
    windSpeed_ = 0D;
    precipitation_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeatherData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            temperature_ = input.readDouble();
            break;
          }
          case 17: {

            humidity_ = input.readDouble();
            break;
          }
          case 25: {

            windSpeed_ = input.readDouble();
            break;
          }
          case 33: {

            precipitation_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lekkss.weathersensor.weathersensorservice.WeatherSensorServiceProto.internal_static_com_lekkss_weathersensor_WeatherData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lekkss.weathersensor.weathersensorservice.WeatherSensorServiceProto.internal_static_com_lekkss_weathersensor_WeatherData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lekkss.weathersensor.weathersensorservice.WeatherData.class, com.lekkss.weathersensor.weathersensorservice.WeatherData.Builder.class);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 1;
  private double temperature_;
  /**
   * <code>double temperature = 1;</code>
   */
  public double getTemperature() {
    return temperature_;
  }

  public static final int HUMIDITY_FIELD_NUMBER = 2;
  private double humidity_;
  /**
   * <code>double humidity = 2;</code>
   */
  public double getHumidity() {
    return humidity_;
  }

  public static final int WIND_SPEED_FIELD_NUMBER = 3;
  private double windSpeed_;
  /**
   * <code>double wind_speed = 3;</code>
   */
  public double getWindSpeed() {
    return windSpeed_;
  }

  public static final int PRECIPITATION_FIELD_NUMBER = 4;
  private double precipitation_;
  /**
   * <code>double precipitation = 4;</code>
   */
  public double getPrecipitation() {
    return precipitation_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (temperature_ != 0D) {
      output.writeDouble(1, temperature_);
    }
    if (humidity_ != 0D) {
      output.writeDouble(2, humidity_);
    }
    if (windSpeed_ != 0D) {
      output.writeDouble(3, windSpeed_);
    }
    if (precipitation_ != 0D) {
      output.writeDouble(4, precipitation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (temperature_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, temperature_);
    }
    if (humidity_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, humidity_);
    }
    if (windSpeed_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, windSpeed_);
    }
    if (precipitation_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, precipitation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lekkss.weathersensor.weathersensorservice.WeatherData)) {
      return super.equals(obj);
    }
    com.lekkss.weathersensor.weathersensorservice.WeatherData other = (com.lekkss.weathersensor.weathersensorservice.WeatherData) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getTemperature())
        == java.lang.Double.doubleToLongBits(
            other.getTemperature()));
    result = result && (
        java.lang.Double.doubleToLongBits(getHumidity())
        == java.lang.Double.doubleToLongBits(
            other.getHumidity()));
    result = result && (
        java.lang.Double.doubleToLongBits(getWindSpeed())
        == java.lang.Double.doubleToLongBits(
            other.getWindSpeed()));
    result = result && (
        java.lang.Double.doubleToLongBits(getPrecipitation())
        == java.lang.Double.doubleToLongBits(
            other.getPrecipitation()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperature()));
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHumidity()));
    hash = (37 * hash) + WIND_SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWindSpeed()));
    hash = (37 * hash) + PRECIPITATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrecipitation()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lekkss.weathersensor.weathersensorservice.WeatherData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lekkss.weathersensor.weathersensorservice.WeatherData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.lekkss.weathersensor.WeatherData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lekkss.weathersensor.WeatherData)
      com.lekkss.weathersensor.weathersensorservice.WeatherDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lekkss.weathersensor.weathersensorservice.WeatherSensorServiceProto.internal_static_com_lekkss_weathersensor_WeatherData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lekkss.weathersensor.weathersensorservice.WeatherSensorServiceProto.internal_static_com_lekkss_weathersensor_WeatherData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lekkss.weathersensor.weathersensorservice.WeatherData.class, com.lekkss.weathersensor.weathersensorservice.WeatherData.Builder.class);
    }

    // Construct using com.lekkss.weathersensor.weathersensorservice.WeatherData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      temperature_ = 0D;

      humidity_ = 0D;

      windSpeed_ = 0D;

      precipitation_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lekkss.weathersensor.weathersensorservice.WeatherSensorServiceProto.internal_static_com_lekkss_weathersensor_WeatherData_descriptor;
    }

    @java.lang.Override
    public com.lekkss.weathersensor.weathersensorservice.WeatherData getDefaultInstanceForType() {
      return com.lekkss.weathersensor.weathersensorservice.WeatherData.getDefaultInstance();
    }

    @java.lang.Override
    public com.lekkss.weathersensor.weathersensorservice.WeatherData build() {
      com.lekkss.weathersensor.weathersensorservice.WeatherData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lekkss.weathersensor.weathersensorservice.WeatherData buildPartial() {
      com.lekkss.weathersensor.weathersensorservice.WeatherData result = new com.lekkss.weathersensor.weathersensorservice.WeatherData(this);
      result.temperature_ = temperature_;
      result.humidity_ = humidity_;
      result.windSpeed_ = windSpeed_;
      result.precipitation_ = precipitation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lekkss.weathersensor.weathersensorservice.WeatherData) {
        return mergeFrom((com.lekkss.weathersensor.weathersensorservice.WeatherData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lekkss.weathersensor.weathersensorservice.WeatherData other) {
      if (other == com.lekkss.weathersensor.weathersensorservice.WeatherData.getDefaultInstance()) return this;
      if (other.getTemperature() != 0D) {
        setTemperature(other.getTemperature());
      }
      if (other.getHumidity() != 0D) {
        setHumidity(other.getHumidity());
      }
      if (other.getWindSpeed() != 0D) {
        setWindSpeed(other.getWindSpeed());
      }
      if (other.getPrecipitation() != 0D) {
        setPrecipitation(other.getPrecipitation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lekkss.weathersensor.weathersensorservice.WeatherData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lekkss.weathersensor.weathersensorservice.WeatherData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double temperature_ ;
    /**
     * <code>double temperature = 1;</code>
     */
    public double getTemperature() {
      return temperature_;
    }
    /**
     * <code>double temperature = 1;</code>
     */
    public Builder setTemperature(double value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double temperature = 1;</code>
     */
    public Builder clearTemperature() {
      
      temperature_ = 0D;
      onChanged();
      return this;
    }

    private double humidity_ ;
    /**
     * <code>double humidity = 2;</code>
     */
    public double getHumidity() {
      return humidity_;
    }
    /**
     * <code>double humidity = 2;</code>
     */
    public Builder setHumidity(double value) {
      
      humidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double humidity = 2;</code>
     */
    public Builder clearHumidity() {
      
      humidity_ = 0D;
      onChanged();
      return this;
    }

    private double windSpeed_ ;
    /**
     * <code>double wind_speed = 3;</code>
     */
    public double getWindSpeed() {
      return windSpeed_;
    }
    /**
     * <code>double wind_speed = 3;</code>
     */
    public Builder setWindSpeed(double value) {
      
      windSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double wind_speed = 3;</code>
     */
    public Builder clearWindSpeed() {
      
      windSpeed_ = 0D;
      onChanged();
      return this;
    }

    private double precipitation_ ;
    /**
     * <code>double precipitation = 4;</code>
     */
    public double getPrecipitation() {
      return precipitation_;
    }
    /**
     * <code>double precipitation = 4;</code>
     */
    public Builder setPrecipitation(double value) {
      
      precipitation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double precipitation = 4;</code>
     */
    public Builder clearPrecipitation() {
      
      precipitation_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lekkss.weathersensor.WeatherData)
  }

  // @@protoc_insertion_point(class_scope:com.lekkss.weathersensor.WeatherData)
  private static final com.lekkss.weathersensor.weathersensorservice.WeatherData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lekkss.weathersensor.weathersensorservice.WeatherData();
  }

  public static com.lekkss.weathersensor.weathersensorservice.WeatherData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherData>
      PARSER = new com.google.protobuf.AbstractParser<WeatherData>() {
    @java.lang.Override
    public WeatherData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeatherData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeatherData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lekkss.weathersensor.weathersensorservice.WeatherData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

