// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeatherSensorService.proto

package com.lekkss.weathersensor.weathersensorservice;

public final class WeatherSensorServiceProto {
  private WeatherSensorServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lekkss_weathersensor_LocationCoordinates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lekkss_weathersensor_LocationCoordinates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lekkss_weathersensor_WeatherData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lekkss_weathersensor_WeatherData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032WeatherSensorService.proto\022\030com.lekkss" +
      ".weathersensor\":\n\023LocationCoordinates\022\020\n" +
      "\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\"_\n\013We" +
      "atherData\022\023\n\013temperature\030\001 \001(\001\022\020\n\010humidi" +
      "ty\030\002 \001(\001\022\022\n\nwind_speed\030\003 \001(\001\022\025\n\rprecipit" +
      "ation\030\004 \001(\0012\366\001\n\024WeatherSensorService\022j\n\022" +
      "GetWeatherForecast\022-.com.lekkss.weathers" +
      "ensor.LocationCoordinates\032%.com.lekkss.w" +
      "eathersensor.WeatherData\022r\n\030GetAverageWe" +
      "atherForcast\022-.com.lekkss.weathersensor." +
      "LocationCoordinates\032%.com.lekkss.weather" +
      "sensor.WeatherData(\001BL\n-com.lekkss.weath" +
      "ersensor.weathersensorserviceB\031WeatherSe" +
      "nsorServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lekkss_weathersensor_LocationCoordinates_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lekkss_weathersensor_LocationCoordinates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lekkss_weathersensor_LocationCoordinates_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_com_lekkss_weathersensor_WeatherData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lekkss_weathersensor_WeatherData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lekkss_weathersensor_WeatherData_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "WindSpeed", "Precipitation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
